services:
  # provider
  hshn_class_matcher.matcher_provider:
    class: Hshn\ClassMatcherBundle\ClassMatcher\ClassMatcherProvider

  # matcher
  hshn_class_matcher.class_matcher.equals.def:
    absract: true
    class: Hshn\ClassMatcher\Matcher\EqualsTo
    arguments: [~]

  hshn_class_matcher.class_matcher.extended.def:
    absract: true
    class: Hshn\ClassMatcher\Matcher\Extended
    arguments: [~]

  hshn_class_matcher.class_matcher.implemented.def:
    absract: true
    class: Hshn\ClassMatcher\Matcher\Implemented
    arguments: [~]

  hshn_class_matcher.class_matcher.anything.def:
    public: false
    class: Hshn\ClassMatcher\Matcher\Anything

  hshn_class_matcher.class_matcher.and.def:
    abstract: true
    class: Hshn\ClassMatcher\Matcher\LogicalAnd
    arguments: [~]

  hshn_class_matcher.class_matcher.or.def:
    abstract: true
    class: Hshn\ClassMatcher\Matcher\LogicalOr
    arguments: [~]
